"""add stock request relationships

Revision ID: 102f69c10d7f
Revises: bb6768ef3fb7
Create Date: 2026-06-24 14:18:41.350404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102f69c10d7f'
down_revision = 'bb6768ef3fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_request', schema=None) as batch_op:
        batch_op.alter_column('requested_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_request', schema=None) as batch_op:
        batch_op.alter_column('requested_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
