"""add quantity_expression to transaction and stock request

Revision ID: b0c771f905d1
Revises: e85960b257aa
Create Date: 2026-07-22 14:29:28.533908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c771f905d1'
down_revision = 'e85960b257aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_expression', sa.String(length=255), nullable=True))

    with op.batch_alter_table('stock_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_expression', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_request', schema=None) as batch_op:
        batch_op.drop_column('quantity_expression')

    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.drop_column('quantity_expression')

    # ### end Alembic commands ###
