"""split size into capacity and neck size

Revision ID: b1a04e152500
Revises: bab8ff7eef08
Create Date: 2026-08-26 09:50:35.359218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a04e152500'
down_revision = 'bab8ff7eef08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neck_size_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_product_neck_size_id', 'size', ['neck_size_id'], ['id']
        )

    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), server_default='CAPACITY', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.drop_column('kind')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_neck_size_id', type_='foreignkey')
        batch_op.drop_column('neck_size_id')

    # ### end Alembic commands ###
