"""add secondary color to product and hex code to color

Revision ID: e53321a8e3e6
Revises: b0c771f905d1
Create Date: 2026-08-20 08:10:21.496088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53321a8e3e6'
down_revision = 'b0c771f905d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('color', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hex_code', sa.String(length=7), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_color_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'color', ['secondary_color_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('secondary_color_id')

    with op.batch_alter_table('color', schema=None) as batch_op:
        batch_op.drop_column('hex_code')

    # ### end Alembic commands ###
