"""Where product images live.

Today they sit on the local disk next to the app. That does not survive the
move to a public storefront: every image request costs a waitress thread,
every nightly backup copies the whole folder, and a container host wipes the
directory on restart.

So nothing outside this module knows where an image actually is. Routes call
`save_image` / `delete_image`, templates call `image_url`, and swapping the
local disk for object storage means adding one class here and setting
STORAGE_BACKEND — not touching the routes or the six templates that render an
image.
"""

import os

from flask import url_for


class LocalStorage:
    """Files on disk, served by the app itself."""

    name = "local"

    def __init__(self, folder):
        self.folder = folder
        os.makedirs(self.folder, exist_ok=True)

    def _path(self, key):
        # keys are generated by utils.images, but never let one escape the
        # upload folder even if a caller passes something unexpected
        safe = os.path.basename(key)
        return os.path.join(self.folder, safe)

    def save(self, data, key):
        with open(self._path(key), "wb") as handle:
            handle.write(data)
        return key

    def delete(self, key):
        if not key:
            return
        path = self._path(key)
        if os.path.exists(path):
            os.remove(path)

    def exists(self, key):
        return bool(key) and os.path.exists(self._path(key))

    def size(self, key):
        path = self._path(key)
        return os.path.getsize(path) if os.path.exists(path) else 0

    def url(self, key):
        if not key:
            return ""
        return url_for("uploaded_file", filename=key)


class R2Storage:
    """Cloudflare R2 — S3-compatible object storage behind Cloudflare's CDN.

    Files are served straight from R2's public URL, so an image request never
    reaches the app: no waitress thread per photo, and nothing to copy into the
    nightly backup. Any other S3-compatible provider works by pointing
    R2_ENDPOINT somewhere else — the code below is plain S3.
    """

    name = "r2"

    # Uploaded names are UUID-prefixed, so a name always maps to the same
    # bytes and can be cached hard.
    CACHE_CONTROL = "public, max-age=2592000, immutable"

    CONTENT_TYPES = {
        "webp": "image/webp",
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "gif": "image/gif",
        "svg": "image/svg+xml",
    }

    def __init__(self, bucket, public_base, endpoint, access_key, secret_key):
        import boto3
        from botocore.config import Config

        self.bucket = bucket
        self.public_base = public_base.rstrip("/")

        self.client = boto3.client(
            "s3",
            endpoint_url=endpoint,
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            # R2 ignores regions but boto3 insists on one
            region_name="auto",
            config=Config(signature_version="s3v4", retries={"max_attempts": 3}),
        )

    def _content_type(self, key):
        ext = key.rsplit(".", 1)[-1].lower() if "." in key else ""
        return self.CONTENT_TYPES.get(ext, "application/octet-stream")

    def save(self, data, key):
        self.client.put_object(
            Bucket=self.bucket,
            Key=key,
            Body=data,
            ContentType=self._content_type(key),
            CacheControl=self.CACHE_CONTROL,
        )
        return key

    def delete(self, key):
        if not key:
            return
        self.client.delete_object(Bucket=self.bucket, Key=key)

    def exists(self, key):
        if not key:
            return False
        from botocore.exceptions import ClientError
        try:
            self.client.head_object(Bucket=self.bucket, Key=key)
            return True
        except ClientError:
            return False

    def size(self, key):
        from botocore.exceptions import ClientError
        try:
            return self.client.head_object(Bucket=self.bucket, Key=key)["ContentLength"]
        except ClientError:
            return 0

    def url(self, key):
        if not key:
            return ""
        return f"{self.public_base}/{key}"


_storage = None


def init_storage(app):
    """Pick a backend and expose `image_url` to templates."""

    global _storage

    backend = os.getenv("STORAGE_BACKEND", "local").lower()

    if backend == "local":
        _storage = LocalStorage(app.config["UPLOAD_FOLDER"])

    elif backend == "r2":
        account = os.getenv("R2_ACCOUNT_ID", "").strip()
        endpoint = os.getenv("R2_ENDPOINT", "").strip() or (
            f"https://{account}.r2.cloudflarestorage.com" if account else ""
        )

        settings = {
            "R2_BUCKET": os.getenv("R2_BUCKET", "").strip(),
            "R2_PUBLIC_BASE": os.getenv("R2_PUBLIC_BASE", "").strip(),
            "R2_ACCESS_KEY_ID": os.getenv("R2_ACCESS_KEY_ID", "").strip(),
            "R2_SECRET_ACCESS_KEY": os.getenv("R2_SECRET_ACCESS_KEY", "").strip(),
        }

        missing = [k for k, v in settings.items() if not v]
        if not endpoint:
            missing.append("R2_ACCOUNT_ID (أو R2_ENDPOINT)")

        if missing:
            raise RuntimeError(
                "STORAGE_BACKEND=r2 بس ناقص بملف .env: " + "، ".join(missing)
            )

        _storage = R2Storage(
            bucket=settings["R2_BUCKET"],
            public_base=settings["R2_PUBLIC_BASE"],
            endpoint=endpoint,
            access_key=settings["R2_ACCESS_KEY_ID"],
            secret_key=settings["R2_SECRET_ACCESS_KEY"],
        )

    else:
        raise RuntimeError(
            f"STORAGE_BACKEND='{backend}' غير مدعوم — المدعوم: local أو r2"
        )

    app.extensions["storage"] = _storage

    @app.context_processor
    def inject_image_url():
        return {"image_url": _storage.url}

    return _storage


def get_storage():
    if _storage is None:
        raise RuntimeError("init_storage(app) لازم تنستدعى قبل استعمال التخزين")
    return _storage


# --- convenience wrappers, so callers never touch the backend object ---

def save_image(data, key):
    return get_storage().save(data, key)


def delete_image(key):
    return get_storage().delete(key)


def image_url(key):
    return get_storage().url(key)
